### ISSUE TITLE
animation cannot work without a error wrong code

### ISSUE THREAD

**Issue by junechen22** [pyqt/maya2016-qt4#2]
I try to make a image repeater ,so i choose animation of QPropertyAnimation as method.
the image will display for 3s
and then clear for 1s , and then display next one. 

normal animation code is:
```

    def imgstart(self,i):
        self.loadimg()
        #i=-1 can clear image in label
        if i== -1:
            self.ui.imgShow_label.clear()
        else:
            animation =QPropertyAnimation(self.ui.imgShow_label,"pos")
            animation.setDuration(500)
            animation.setStartValue(QPoint(360, 50))
            animation.setEndValue(QPoint(10,50))
            animation.setEasingCurve(QEasingCurve.InOutCubic)
            #display image
            self.ui.imgShow_label.setPixmap(self.pixmap[i])
            #image canimation
            animation.start()
```
By common sense ,this code shoud work successfully.but ,it can't.
i add a wrong code follow the code  by accident:
```
for i in 1:
                pass
```
The animation moves!!!
the wrong code made this animation moves!!also print error message:
```
Traceback (most recent call last):
  File "error_code_rate.py", line 191, in imgstart
    for i in 1:
TypeError: 'int' object is not iterable

```
This is a strange bug

**Comment by mottosso** [comment]
That does sound odd, best to report this to the PyQt developers here: https://www.riverbankcomputing.com/mailman/listinfo/pyqt
